variables:
  REDHAWK_VERSION: '2.0.4'
  FRONTEND_VERSION: '2.3.4'

stages:
  - build
  - build-2
  - build-3
  - test
  - deploy
  - deploy-test

.rpmbuild: &rpmbuild 
  image: redhawk/buildenv:$PLATFORM
  script:
    - cd $PROJECT
    - tar --transform "s,^,$PROJECT-$REDHAWK_VERSION/,S" -czf /root/rpmbuild/SOURCES/$PROJECT-$REDHAWK_VERSION.tar.gz *
    - yum install -y ../*.rpm || true
    - yum-builddep -y $PROJECT.spec 
    - bash -lc 'rpmbuild -bb $PROJECT.spec'
    - cp -rv /root/rpmbuild/RPMS/*/*.rpm ..

.core_rpmbuild: &core_rpmbuild
  image: redhawk/buildenv:$PLATFORM
  stage: build
  script:
    - cd $PROJECT
    - tar --transform "s,^,$PROJECT-$REDHAWK_VERSION/,S" -czf /root/rpmbuild/SOURCES/$PROJECT-$REDHAWK_VERSION.tar.gz *
    - yum-builddep -y src/releng/redhawk.spec
    - rpmbuild -bb src/releng/redhawk.spec
    - cp -rv /root/rpmbuild/RPMS/*/*.rpm ..
  artifacts:
    paths:
      - redhawk*.rpm

.frontend_rpmbuild: &frontend_rpmbuild
  image: redhawk/buildenv:$PLATFORM
  stage: build-3
  script:
    - cd $PROJECT
    - tar --transform "s,^,$PROJECT-$FRONTEND_VERSION/,S" -czf /root/rpmbuild/SOURCES/$PROJECT-$FRONTEND_VERSION.tar.gz *
    - yum install -y ../*.rpm || true
    - yum-builddep -y $PROJECT.spec 
    - bash -lc 'rpmbuild -bb $PROJECT.spec'
    - cp -rv /root/rpmbuild/RPMS/*/*.rpm ..
  artifacts:
    paths:
      - frontend*.rpm

core-el6:
  variables:
    PROJECT: 'redhawk'
    PLATFORM: 'el6'
  <<: *core_rpmbuild

core-el7:
  variables:
    PROJECT: 'redhawk'
    PLATFORM: 'el7'
  <<: *core_rpmbuild

codegen-el6:
  variables:
    PROJECT: 'redhawk-codegen'
    PLATFORM: 'el6'
  stage: build
  <<: *rpmbuild
  artifacts:
    paths:
      - redhawk*.rpm

codegen-el7:
  variables:
    PROJECT: 'redhawk-codegen'
    PLATFORM: 'el7'
  stage: build
  <<: *rpmbuild
  artifacts:
    paths:
      - redhawk*.rpm

bulkio-el6:
  variables:
    PROJECT: 'bulkioInterfaces'
    PLATFORM: 'el6'
  stage: build-2
  dependencies:
    - core-el6
  <<: *rpmbuild
  artifacts:
    paths:
      - bulkio*.rpm

bulkio-el7:
  variables:
    PROJECT: 'bulkioInterfaces'
    PLATFORM: 'el7'
  stage: build-2
  dependencies:
    - core-el7
  <<: *rpmbuild
  artifacts:
    paths:
      - bulkio*.rpm

GPP-el6:
  variables:
    PROJECT: 'GPP'
    PLATFORM: 'el6'
  stage: build-2
  dependencies:
    - core-el6
  <<: *rpmbuild
  artifacts:
    paths:
      - GPP*.rpm

GPP-el7:
  variables:
    PROJECT: 'GPP'
    PLATFORM: 'el7'
  stage: build-2
  dependencies:
    - core-el7
  <<: *rpmbuild
  artifacts:
    paths:
      - GPP*.rpm

burstio-el6:
  variables:
    PROJECT: 'burstioInterfaces'
    PLATFORM: 'el6'
  stage: build-3
  dependencies:
    - core-el6
    - bulkio-el6
  <<: *rpmbuild
  artifacts:
    paths:
      - burstio*.rpm

burstio-el7:
  variables:
    PROJECT: 'burstioInterfaces'
    PLATFORM: 'el7'
  stage: build-3
  dependencies:
    - core-el7
    - bulkio-el7
  <<: *rpmbuild
  artifacts:
    paths:
      - burstio*.rpm

frontend-el6:
  variables:
    PROJECT: 'frontendInterfaces'
    PLATFORM: 'el6'
  dependencies:
    - core-el6
    - bulkio-el6
  <<: *frontend_rpmbuild

frontend-el7:
  variables:
    PROJECT: 'frontendInterfaces'
    PLATFORM: 'el7'
  dependencies:
    - core-el7
    - bulkio-el7
  <<: *frontend_rpmbuild

test:install:el6:
  image: centos:6
  stage: test
  dependencies:
    - core-el6
    - bulkio-el6
    - burstio-el6
    - GPP-el6
    - frontend-el6
    - codegen-el6
  script:
    - printf "[redhawk-deps]\nname=redhawk-deps\nbaseurl=$REDHAWK_DEPS_URL/el6/x86_64\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/redhawk-deps.repo
    - yum install -y epel-release
    - yum install -y *.rpm

deploy:el6:
  image: redhawkci/deploy
  stage: deploy
  tags:
    - deployment
  dependencies:
    - core-el6
    - bulkio-el6
    - burstio-el6
    - GPP-el6
    - frontend-el6
    - codegen-el6
  script:
    - mkdir output 
    - cp *.rpm output
    - cd output
    - createrepo .
    - eval "$(ssh-agent -s)"
    - ssh-add
    - rsync -avz --delete * $PUBLISH_URL:$PUBLISH_PATH/$CI_BUILD_REF_NAME/el6/x86_64/
  artifacts:
    paths:
      - output/*.rpm
      - output/**/*

test:deployed:el6:
  image: centos:6
  stage: deploy-test
  dependencies: 
    - deploy:el6
  script:
    - printf "[redhawk-deps]\nname=redhawk-deps\nbaseurl=$REDHAWK_DEPS_URL/el6/x86_64\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/redhawk-deps.repo
    - printf "[redhawk]\nname=redhawk\nbaseurl=$PUBLISH_WEB_URL/$CI_BUILD_REF_NAME/el6/x86_64/\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/redhawk.repo
    - yum install -y epel-release
    - yum install -y redhawk-devel redhawk-* bulkio* burstio* frontend* GPP*
